
pages: # the job must be named pages
  image: node:latest
  stage: deploy
  before_script:
    - apt-get update -y
    - apt-get install -y make python3-pip curl jq zip wget unzip
  script:
    - npm ci
    - nodejs generateManifest.js
    - npm run build
    - bash tools/update_fonts.sh
    - mv public public-vue # GitLab Pages hooks on the public folder
    - mv dist public # rename the dist folder (result of npm run build)
    - find public \( -name '*.html' -o -name '*.css' -o -name '*.js' \) -print0 | xargs -0 gzip -9 -kv
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
    - master